name 'ithempel-ppa'
version '1.0.1'
source 'git://github.com/ithempel/ppa'
author 'Sebastian Hempel'
license 'Apache 2.0'
summary 'defines for PPAs'
description 'Defines to handle the management of PPAs'
project_page 'https://github.com/ithempel/ppa'
